AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Version:
    Type: String
    Description: Git Tag of this deployment
  ServiceStage:
    Type: String
    Description: The name of the service
  RoleARN:
    Type: String
    Description: The ARN for the role to execute under
  CodeBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  CodePath:
    Type: String
    Description: Location of template files
  DirectEndpoint:
    Type: String
    Description: Contentful direct url
  LogRetention:
    Type: Number
    Description: days
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  MapTimeout:
    Type: Number
    Description: seconds
    MinValue: 1
    MaxValue: 300
    Default: 30
  MapMemorySize:
    Type: Number
    Description: MB
    AllowedValues: [128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832, 896, 960, 1024, 1088, 1152, 1216, 1280, 1344, 1408, 1472, 1536]
    Default: 128

Outputs:
  MapArn:
    Value: !GetAtt MapQueryFunction.Arn
  MapLogs:
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#logStream:group=${MapQueryFunctionLogs}

Resources:
  MapQueryFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Sub ${CodePath}/src.zip
      FunctionName: !Sub ${ServiceStage}-mapquery
      Handler: src/main.handler
      Role: !Ref RoleARN
      Runtime: python2.7
      Timeout: !Ref MapTimeout
      MemorySize: !Ref MapMemorySize
      Environment:
        Variables:
          VERSION: !Ref Version
          DIRECT_ENDPOINT: !Ref DirectEndpoint
  MapQueryFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${MapQueryFunction}
      RetentionInDays: !Ref LogRetention
  MapQueryPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MapQueryFunction
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
